# On définit les stages
stages:
  - tests
  - build
  - livraison

# On définit une variable IMAGE_TAG qui va être composé de l'adresse de votre registry + la référence du commit.
variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

# Votre premier job qui va juste executer la commande test sur le fichier dans un conteneur "bash"
test-index:
  stage: tests
  tags:
    - container
  image: bash
  script:
    - test -s index.html

# On se log au registry, on build, avant de push l'image Docker
build-push:
  stage: build
  tags:
    - cli
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

# On execute sur le runner prod un run du conteneur après s'être log sur le registry Docker. On supprime bien sur le Docker précédent s'il existe 
deploy:
  stage: livraison
  tags:
    - prod
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker rm -f supdevinci &>/dev/null && echo 'Removed old container'
    - docker run -d --name supdevinci -p 99:80 $IMAGE_TAG 
